### ISSUE TITLE
Implement multiple routing strategies support

### ISSUE THREAD

**Issue by umpirsky** [umpirsky/UmpirskyI18nRoutingBundle#1]
For the start this two are enough:

- Prefix all routes for all locales.
- Prefix all routes for all locales except default.

**Comment by kbond** [comment]
I again dropped in this bundle as a replacement for the jms one in a project. Everything worked as expected except these 2 items:

1. Had to duplicate a couple routes without i18n so I could adjust the order (#5) - not a big deal really.
2. The login/logout no longer works for i18n routes. Since you can only choose a single path or a route in your security bundle settings, only the `non-i18n` route works. I think I can switch to using symfony guard and get this to work but do you have any other ideas?

**Comment by umpirsky** [comment]
@kbond 

1. I will address this.
1. The workaround is to disable i18n for login/logout routes. Is there a case when they are needed?

Thanks for the feedback!

**Comment by kbond** [comment]
1. Cool
2. Yeah but then the interface/errors wouldn't be translated. I think why the jms bundle works is its router overrides the [matching of routes](https://github.com/schmittjoh/JMSI18nRoutingBundle/blob/master/Router/I18nRouter.php#L150). Think this bundle could do something similar?

**Comment by kbond** [comment]
I added POC of what I mean in #13

**Comment by umpirsky** [comment]
@kbond Regarding 2. routes that render login/registration page, can be i18n, but routes that do login/registration, can be separate POST routes that have i18n disabled.

**Comment by kbond** [comment]
Yeah, true enough.
