### ISSUE TITLE
`routing.loader` service is private deprecation in Symfony 3.4

### ISSUE THREAD

**Issue by kbond** [umpirsky/UmpirskyI18nRoutingBundle#17]
I'm getting this deprecation when upgrading to Symfony 3.4:

> User Deprecated: The "routing.loader" service is private, getting it from the container is deprecated since Symfony 3.2 and will fail in 4.0. You should either make the service public, or stop using the container directly and use dependency injection instead.

I isolated this bundle as being the cause but I'm not sure why...

**Comment by stof** [comment]
this is because the custom logic used to decorate the service does not properly deal with the fact that services become private by default in 3.4 (with a BC layer), and so turns the service as private during this logic.

the simplest fix is to use the service decoration feature of Symfony instead of emulating it. This way, there is no need to maintain the logic over time (Symfony does it instead)

**Comment by kbond** [comment]
Thanks @stof
